# -*- coding: utf-8 -*-
"""Task 1 Navya Jain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQYd8CFFVZCkOjTeu5SPUStiq_kB_ZO6
"""

import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

customers = pd.read_csv('Customers.csv')
transactions = pd.read_csv('Transactions.csv')

customer_transactions = transactions.groupby('CustomerID').agg(
    total_spent=('TotalValue', 'sum'),
    frequency=('Quantity', 'sum')
).reset_index()

customer_data = pd.merge(customers, customer_transactions, on='CustomerID', how='left')

customer_data['total_spent'] = customer_data['total_spent'].fillna(0)
customer_data['frequency'] = customer_data['frequency'].fillna(0)

features = ['total_spent', 'frequency']
scaler = StandardScaler()
scaled_features = scaler.fit_transform(customer_data[features])

cos_sim = cosine_similarity(scaled_features)

lookalike_results = {}
for idx, customer_id in enumerate(customer_data['CustomerID']):
    if customer_id in [f"C{str(i).zfill(4)}" for i in range(1, 21)]:
        similarity_scores = cos_sim[idx]
        similar_customers_idx = similarity_scores.argsort()[-4:-1]
        similar_customers = [(customer_data['CustomerID'][i], similarity_scores[i]) for i in similar_customers_idx]
        lookalike_results[customer_id] = similar_customers

lookalike_df = pd.DataFrame([
    {'CustomerID': cust_id, 'Lookalikes': lookalikes}
    for cust_id, lookalikes in lookalike_results.items()
])
lookalike_df.to_csv('Lookalike.csv', index=False)

print("Lookalike.csv has been generated successfully!")